# Generated by Django 4.2 on 2025-12-06 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_latin', message='Только латинские символы, цифры и нижнее подчёркивание.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
