# Generated by Django 4.2 on 2025-12-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
