# Generated by Django 4.2 on 2025-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(max_length=2500),
        ),
    ]
