# Generated by Django 4.2 on 2025-12-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='database.place'),
        ),
    ]
